package com.pronaycoding.blankee.core.data.repository

import com.pronaycoding.blankee.core.database.entities.PresetEntity
import kotlinx.coroutines.flow.Flow

/**
 * Repository interface for preset data access operations.
 *
 * This interface defines a contract for preset persistence, abstracting the underlying database implementation.
 * It provides high-level operations for managing presets without exposing database details to the caller.
 *
 * @see PresetRepositoryImpl for the concrete implementation
 * @see PresetEntity for the data model
 * @see PresetDao for lower-level database access
 */
interface PresetRepository {

    /**
     * Observes all presets as a continuous Flow.
     *
     * The returned Flow emits a new list of presets whenever changes occur in the database.
     * This enables reactive UI updates when presets are added, modified, or deleted.
     * The Flow is a cold stream that starts emitting when collected.
     *
     * @return A Flow of lists containing all presets
     */
    fun observePresets(): Flow<List<PresetEntity>>

    /**
     * Saves a new preset to the database.
     *
     * @param entity The [PresetEntity] to save
     * @return The ID of the newly created preset (auto-generated by the database)
     * @throws Exception if the save operation fails
     */
    suspend fun savePreset(entity: PresetEntity): Long

    /**
     * Deletes a preset by its ID.
     *
     * @param id The ID of the preset to delete
     * @throws Exception if the delete operation fails
     */
    suspend fun deletePreset(id: Long)
}
