package com.pronaycoding.blankee.core.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a custom sound file uploaded by the user in the database.
 *
 * Custom sounds extend the built-in sound library, allowing users to import their own audio files
 * (e.g., personal recordings, nature sounds) and use them in sound presets. The audio file itself
 * is stored on the file system, while this entity stores metadata and the file path reference.
 *
 * @property id Unique identifier for the custom sound (auto-generated by the database)
 * @property displayName User-friendly name for the custom sound as it appears in the UI
 * @property filePath Full path or URI to the audio file on the device (e.g., "/data/user/0/.../sound.mp3")
 * @property createdAt Timestamp (in milliseconds) when the custom sound was added, defaults to current system time
 *
 * @see CustomSoundDao for database access operations
 * @see BlankeeDatabase for the database definition
 */
@Entity(tableName = "custom_sounds")
data class CustomSoundEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val displayName: String,
    val filePath: String,
    val createdAt: Long = System.currentTimeMillis()
)
