package com.pronaycoding.blankee.core.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a saved sound preset in the database.
 *
 * A preset is a combination of built-in sounds and/or custom sounds, each with specific volume levels,
 * that users can save and restore for quick playback. For example, a user might create a "Relaxing Evening"
 * preset with rain at 60% volume and birds at 40% volume.
 *
 * @property id Unique identifier for the preset (auto-generated by the database)
 * @property name User-friendly name for the preset (e.g., "Relaxing Evening")
 * @property builtInVolumesJson JSON string mapping built-in sound indices to their volume levels (0.0 - 1.0)
 * @property customVolumesJson JSON string mapping custom sound IDs to their volume levels (0.0 - 1.0)
 * @property createdAt Timestamp (in milliseconds) when the preset was created, defaults to current system time
 *
 * @see PresetDao for database access operations
 * @see BlankeeDatabase for the database definition
 */
@Entity(tableName = "presets")
data class PresetEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    val builtInVolumesJson: String,
    val customVolumesJson: String,
    val createdAt: Long = System.currentTimeMillis()
)
